const postActionTypes = {
  FETCH_COLLECTION_START: "FETCH_COLLECTION_START",
  FETCH_COLLECTION_SUCCESS: "FETCH_COLLECTION_SUCCESS",
  FETCH_COLLECTION_FAILURE: "FETCH_COLLECTION_FAILURE",

  FETCH_POST_START: "FETCH_POST_START",
  FETCH_POST_SUCCESS: "FETCH_POST_SUCCESS",
  FETCH_POST_FAILURE: "FETCH_POST_FAILURE",

  CREATE_NEW_POST_START: "CREATE_NEW_POST_START",
  CREATE_NEW_POST_SUCCESS: "CREATE_NEW_POST_SUCCESS",
  CREATE_NEW_POST_FAILURE: "CREATE_NEW_POST_FAILURE",
};

export default postActionTypes;
