const userActionTypes = {
  FETCH_USER_POSTS_START: "FETCH_USER_POSTS_START",
  FETCH_USER_POSTS_SUCCESS: "FETCH_USER_POSTS_SUCCESS",
  FETCH_USER_POSTS_FAILURE: "FETCH_USER_POSTS_FAILURE",

  FETCH_USER_NOTIFICATIONS_START: "FETCH_USER_NOTIFICATIONS_START",
  FETCH_USER_NOTIFICATIONS_SUCCESS: "FETCH_USER_NOTIFICATIONS_SUCCESS",
  FETCH_USER_NOTIFICATIONS_FAILURE: "FETCH_USER_NOTIFICATIONS_FAILURE",

  CREATE_NEW_POST_START: "CREATE_NEW_POST_START",
  CREATE_NEW_POST_SUCCESS: "CREATE_NEW_POST_SUCCESS",
  CREATE_NEW_POST_FAILURE: "CREATE_NEW_POST_FAILURE",

  VOTE_ON_POST_START: "VOTE_ON_POST_START",
  VOTE_ON_POST_SUCCESS: "VOTE_ON_POST_SUCCESS",
  VOTE_ON_POST_FAILURE: "VOTE_ON_POST_FAILURE",
};

export default userActionTypes;
